version: '3.8'

services:
  # SPIRE Server
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.8.5
    container_name: gdc-spire-server
    hostname: spire-server
    volumes:
      - ./configs/spire/server:/opt/spire/conf/server:ro
      - spire-server-data:/opt/spire/data/server
      - spire-server-socket:/tmp/spire-server/private
    ports:
      - "8081:8081"   # SPIRE Server API
    command: ["-config", "/opt/spire/conf/server/server.conf"]
    networks:
      - gdc-network
    healthcheck:
      test: ["CMD", "/opt/spire/bin/spire-server", "healthcheck", "-socketPath", "/tmp/spire-server/private/api.sock"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # SPIRE Agent
  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.8.5
    container_name: gdc-spire-agent
    hostname: spire-agent
    depends_on:
      spire-server:
        condition: service_healthy
    volumes:
      - ./configs/spire/agent:/opt/spire/conf/agent:ro
      - spire-agent-data:/opt/spire/data/agent
      - spire-agent-socket:/tmp/spire-agent/public
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]
    networks:
      - gdc-network
    healthcheck:
      test: ["CMD", "/opt/spire/bin/spire-agent", "healthcheck", "-socketPath", "/tmp/spire-agent/public/api.sock"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # SPIRE OIDC Discovery Provider (optional, for web-based authentication)
  spire-oidc:
    image: ghcr.io/spiffe/oidc-discovery-provider:1.8.5
    container_name: gdc-spire-oidc
    depends_on:
      spire-server:
        condition: service_healthy
    volumes:
      - ./configs/spire/oidc:/opt/spire-oidc/conf:ro
      - spire-server-socket:/tmp/spire-server/private:ro
    ports:
      - "8082:8080"   # OIDC Discovery endpoint
    command: ["-config", "/opt/spire-oidc/conf/oidc-discovery-provider.conf"]
    networks:
      - gdc-network
    profiles:
      - oidc

  # GDC with SPIFFE authentication
  gdc-spiffe:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gdc-spiffe-app
    depends_on:
      spire-agent:
        condition: service_healthy
      ydb:
        condition: service_healthy
      nats:
        condition: service_healthy
    environment:
      - GDC_DATABASE_ENDPOINT=grpc://ydb:2136
      - GDC_EVENTBUS_URL=nats://nats:4222
      - GDC_TELEMETRY_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - GDC_SECURITY_SPIFFE_SOCKET_PATH=unix:///tmp/spire-agent/public/api.sock
      - GDC_SECURITY_TLS_ENABLED=true
      - GDC_SECURITY_TRUST_DOMAIN=gdc.local
      - GDC_SECURITY_SERVICE_ID=spiffe://gdc.local/gdc-server
      - GDC_LOGGING_LEVEL=debug
    ports:
      - "8443:8443"   # HTTPS API with mTLS
      - "9443:9443"   # gRPC API with mTLS
      - "9091:9091"   # Prometheus metrics
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
      - spire-agent-socket:/tmp/spire-agent/public:ro
    networks:
      - gdc-network
    restart: unless-stopped
    profiles:
      - spiffe

volumes:
  spire-server-data:
    driver: local
  spire-agent-data:
    driver: local
  spire-server-socket:
    driver: local
  spire-agent-socket:
    driver: local
  go_mod_cache:
    driver: local

networks:
  gdc-network:
    external: true