# Global Data Controller Configuration Example

server:
  host: "0.0.0.0"
  port: 8080
  grpc_port: 9090
  read_timeout: "30s"
  write_timeout: "30s"

database:
  endpoint: "grpc://localhost:2136"
  database: "/local"
  credentials: ""

eventbus:
  url: "nats://localhost:4222"
  cluster_id: "gdc-cluster"
  client_id: "gdc-server"

telemetry:
  enabled: true
  prometheus_port: 9091
  jaeger_endpoint: "http://localhost:14268/api/traces"
  service_name: "global-data-controller"
  service_version: "1.0.0"
  sample_rate: 1.0

security:
  # SPIFFE/SPIRE configuration
  spiffe_socket_path: "unix:///tmp/spire-agent/public/api.sock"
  tls_enabled: true
  trust_domain: "gdc.local"
  service_id: "spiffe://gdc.local/gdc-server"
  
  # List of authorized SPIFFE IDs that can connect to this service
  authorized_ids:
    - "spiffe://gdc.local/scheduler"
    - "spiffe://gdc.local/orchestrator"
    - "spiffe://gdc.local/policy-engine"
    - "spiffe://gdc.local/cluster-adapter"
    - "spiffe://gdc.local/admin-ui"

logging:
  level: "info"
  format: "json"
  output_path: "stdout"
  error_path: "stderr"