global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gdc'
    static_configs:
      - targets: ['gdc:9091']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    scrape_interval: 10s

  - job_name: 'ydb'
    static_configs:
      - targets: ['ydb:8765']
    scrape_interval: 10s